### PR TITLE
make sure _next calls callback asynchronously

### PR DESCRIPTION
**Pull request by mvayngrib**
in the last "else" statement of _next, onInitComplete() calls the callback synchronously

### CODE REVIEW

**Comment by nolanlawson** [comment]
Thanks for the PR. I want to merge it, but we need to get our automated tests back up and running, now that Testling is down. :( I'll do taht, then merge.

**Comment by nolanlawson** [comment]
To be clear, I would totally just test your stuff locally and call that good, but IMO this is a module that *really* needs to work in, like, every browser ever, including IE 8. So we gotta be careful.

**Comment by mvayngrib** [comment]
@nolanlawson absolutely agree

**Comment by nolanlawson** [comment]
Tests are up and running again, so I can confirm that this is okay. However, I see a couple issues that I'd like to fix:

1. Leaking the `arguments` object,
2. `._isAsync` seems hacky; there ought to be a better way to only wrap it once.

I'm happy to just apply these fixes myself, though, since I realize this PR has sat around for a long time.

**Comment by nolanlawson** [comment]
Closing in favor of #69, which also contains your commits. Thanks for reporting!

**Comment by mvayngrib** [comment]
@nolanlawson agree with your comments. However, can we avoid penalizing every _next after onInitComplete with a process.nextTick?

**Comment by nolanlawson** [comment]
@mvayngrib I'm not sure how else we could solve the Zalgo problem without basically wrapping the whole `onInitComplete` in a `process.next()` (see how I solved it in #69). I mean, ultimately we will have to do a `process.next()` anyway, right?

**Comment by nolanlawson** [comment]
BTW since you seem to be online right now, we can meet up on Freenode IRC in the ##level room if you want.

**Comment by mvayngrib** [comment]
@nolanlawson don't see you in ##level. Then again I suck at using irc, so I might only think I'm there

**Comment by mvayngrib** [comment]
re: process.nextTick, you're right, I did too many nextTicks in my head

**Comment by nolanlawson** [comment]
@mvayngrib I made a typo; the room is called `##leveldb`. And yeah, there are two hashes; don't ask me why. :)

**Pull request closed without merging**
