### PR TITLE
bypass getItem on keys-only db streams (rebased)

### PR DESCRIPTION
**Pull request by nolanlawson**
Rebased version of #65 so we can test in Travis.

### CODE REVIEW

**Comment by nolanlawson** [comment]
@mvayngrib I re-rebased, but it appears to be failing `npm test`. Not sure if it's due to a mistake I made while rebasing, or if it's a true failure:

```
# bypasses getItem for keys-only db streams

/Users/nolan/workspace/localstorage-down/node_modules/tape/index.js:75
        throw err
        ^
OpenError: Cannot read property 'substring' of null
    at /Users/nolan/workspace/localstorage-down/node_modules/levelup/lib/levelup.js:114:34
    at /Users/nolan/workspace/localstorage-down/taskqueue.js:29:21
    at /Users/nolan/workspace/localstorage-down/node_modules/argsarray/index.js:14:18
    at /Users/nolan/workspace/localstorage-down/localstorage.js:33:16
    at Immediate._onImmediate (/Users/nolan/workspace/localstorage-down/localstorage-core.js:28:5)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```

**Comment by mvayngrib** [comment]
bug in localstorage-memory. Submitted a [PR](https://github.com/gr2m/localstorage-memory/pull/2)

**Comment by nolanlawson** [comment]
Nice catch!

**Comment by nolanlawson** [comment]
closing in favor of #78, we'll get there someday...

**Pull request closed without merging**
